port: 8080
redis:
  host: "119.23.252.204"
  port: 6379
  password: ""
  db: 0
  pool_size: 100
minIO:
  endpoint: "119.23.252.204:9000"
  username: "username"
  password: "password"
  accessKeyID: "minioadmin"
  secretAccessKey: "minioadmin"
mongo:
  name: "dousheng"
  host: "125.73.58.176:5208"
  user: "chaiquan"
  pwd:  "qwer1234"
rabbitMQ:
  host: "114.55.177.229:5672"
  user: "admin"
  pwd: "admin"
  vhost: "admin"
bucket:
  feed: "userfeed"
Video:
  address: "cover/"


